"use client";

import { useState } from "react";
import { motion } from "motion/react";
import { Edit3, Mail, MapPin, Phone, UserRound } from "lucide-react";
import ProfileEditForm from "./ProfileEditForm";

type Profile = { phone?: string | null; location?: string | null; experience?: string | null; linkedin?: string | null; github?: string | null; portfolio?: string | null; skills?: { name: string }[]; education?: { institution: string; degree?: string | null; field?: string | null }[]; projects?: { name: string; description?: string | null }[]; certifications?: { name: string; issuer?: string | null }[] };

export default function ProfileView({ user, candidateProfile }: { user: { name: string; email: string; role: string; image?: string | null }; candidateProfile?: Profile | null }) {
  const [editing, setEditing] = useState(false);
  if (editing) return <div className="w-full"><button onClick={() => setEditing(false)} className="mb-4 text-sm font-semibold text-white/70 hover:text-white">← Back to profile</button><ProfileEditForm initialName={user.name} email={user.email} initialProfile={candidateProfile} /></div>;
  const details = [{ label: "Email", value: user.email, icon: Mail }, { label: "Phone", value: candidateProfile?.phone, icon: Phone }, { label: "Location", value: candidateProfile?.location, icon: MapPin }];
  return <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="w-full max-w-4xl rounded-3xl border border-white/10 bg-white p-6 shadow-2xl sm:p-10"><div className="flex flex-col gap-6 border-b border-slate-200 pb-8 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-linear-to-br from-indigo-500 to-purple-600 text-2xl font-bold text-white">{user.name.slice(0, 1).toUpperCase()}</div><div><h1 className="text-3xl font-bold text-slate-950">{user.name}</h1><p className="mt-1 text-sm font-medium text-blue-600">{user.role}</p></div></div><button onClick={() => setEditing(true)} className="inline-flex h-11 items-center justify-center rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white hover:bg-slate-800"><Edit3 className="mr-2 h-4 w-4" />Edit profile</button></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{details.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><Icon className="h-5 w-5 text-blue-600" /><p className="mt-3 text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-medium text-slate-800">{value || "Not added yet"}</p></div>)}</div>{candidateProfile && <div className="mt-8 space-y-6"><ProfileSection title="Professional details"><Info label="Experience" value={candidateProfile.experience} /><Info label="LinkedIn" value={candidateProfile.linkedin} /><Info label="GitHub" value={candidateProfile.github} /><Info label="Portfolio" value={candidateProfile.portfolio} /></ProfileSection><ProfileSection title="Skills"><Tags items={candidateProfile.skills?.map(item => item.name) ?? []} /></ProfileSection><ProfileSection title="Education"><List items={candidateProfile.education?.map(item => [item.institution, [item.degree, item.field].filter(Boolean).join(" · ")]) ?? []} /></ProfileSection><ProfileSection title="Projects"><List items={candidateProfile.projects?.map(item => [item.name, item.description]) ?? []} /></ProfileSection><ProfileSection title="Certifications"><List items={candidateProfile.certifications?.map(item => [item.name, item.issuer]) ?? []} /></ProfileSection></div>}</motion.section>;
}

function ProfileSection({ title, children }: { title: string; children: React.ReactNode }) { return <div><h2 className="mb-3 text-lg font-bold text-slate-950">{title}</h2><div className="rounded-2xl border border-slate-200 p-4">{children}</div></div>; }
function Info({ label, value }: { label: string; value?: string | null }) { return <p className="mb-2 text-sm text-slate-600 last:mb-0"><strong className="text-slate-800">{label}:</strong> {value || "Not added yet"}</p>; }
function Tags({ items }: { items: string[] }) { return items.length ? <div className="flex flex-wrap gap-2">{items.map(item => <span key={item} className="rounded-full bg-blue-50 px-3 py-1 text-sm font-medium text-blue-700">{item}</span>)}</div> : <p className="text-sm text-slate-500">No skills added yet.</p>; }
function List({ items }: { items: (string | null | undefined)[][] }) { return items.length ? <div className="space-y-3">{items.map((item, index) => <div key={`${item[0]}-${index}`}><p className="font-semibold text-slate-800">{item[0]}</p>{item[1] && <p className="text-sm text-slate-500">{item[1]}</p>}</div>)}</div> : <p className="text-sm text-slate-500">Nothing added yet.</p>; }
