"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Eye, EyeOff, KeyRound, Loader2 } from "lucide-react";
import { motion } from "motion/react";
import { toast } from "sonner";
import { resetPasswordAction } from "@/app/(common)/(authServices)/reset-password/_action";

export default function ResetPasswordForm({ email }: { email: string }) {
  const router = useRouter(); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (otp.length !== 6) return setError("Enter the 6-digit reset code."); if (password.length < 8) return setError("Password must be at least 8 characters."); if (password !== confirm) return setError("Passwords do not match."); setBusy(true); const result = await resetPasswordAction(email, otp, password); setBusy(false); if (!result.success) return setError(result.message ?? "Unable to reset password."); toast.success("Password reset successful"); router.replace("/login"); };
  return <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="w-full max-w-md rounded-3xl border border-white/10 bg-white p-6 shadow-2xl sm:p-10"><div className="mb-8 text-center"><div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><KeyRound className="h-7 w-7" /></div><h1 className="text-3xl font-bold text-slate-950">Create new password</h1><p className="mt-2 text-sm leading-6 text-slate-500">Use the code sent to <strong className="text-slate-700">{email || "your email"}</strong>.</p></div><form onSubmit={submit} className="space-y-5"><input required inputMode="numeric" maxLength={6} value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="6-digit reset code" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-center tracking-[0.35em] outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20" /><label className="block text-sm font-medium text-slate-700">New password<span className="relative mt-2 block"><input required minLength={8} type={show ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 pr-12 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20" placeholder="At least 8 characters" /><button type="button" onClick={() => setShow(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-slate-400">{show ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></span></label><input required minLength={8} type={show ? "text" : "password"} value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Confirm new password" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20" />{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="flex h-12 w-full items-center justify-center rounded-xl bg-slate-950 font-semibold text-white hover:bg-slate-800 disabled:opacity-70">{busy ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Updating password...</> : "Reset password"}</button></form><p className="mt-7 text-center text-sm"><Link href="/login" className="font-semibold text-blue-600 hover:underline">Back to sign in</Link></p></motion.div>;
}
